AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Designer':
    4470a6ad-164a-4077-b5ad-be6e224b4039:
      size:
        width: 60
        height: 60
      position:
        x: 560
        'y': 190
      z: 0
      embeds: []
Resources:
  DLMBackup:
    Type: 'AWS::DLM::LifecyclePolicy'
    Properties:
      Description: Daily Snapshots 12 versions
      State: DISABLED
      ExecutionRoleArn: >-
        arn:aws:iam::747875404488:role/service-role/AWSDataLifecycleManagerDefaultRoleForAMIManagement
      PolicyDetails:
        ResourceTypes:
          - INSTANCE
        PolicyType: IMAGE_MANAGEMENT
        TargetTags:
          - Key: ISOBackup
            Value: Daily14version
        Parameters:
          NoReboot: true
        Schedules:
          - Name: Daily Snapshots
            VariableTags:
              - Key: instance-id
                Value: $(instance-id)
            TagsToAdd:
              - Key: type
                Value: DailySnapshots
            CreateRule:
              Interval: 24
              IntervalUnit: HOURS
              Times:
                - '23:00'
            RetainRule:
              Count: 1
              Interval: 14
              IntervalUnit: DAYS
            CopyTags: true
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 4470a6ad-164a-4077-b5ad-be6e224b4039
